model_list:
  - model_name: minimax-m2.5
    litellm_params:
      model: nvidia_nim/minimaxai/minimax-m2.5
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: nvidia_nim/minimaxai/minimax-m2.5
    litellm_params:
      model: nvidia_nim/minimaxai/minimax-m2.5
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: kimi-k2.5
    litellm_params:
      model: nvidia_nim/moonshotai/kimi-k2.5
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: nvidia_nim/moonshotai/kimi-k2.5
    litellm_params:
      model: nvidia_nim/moonshotai/kimi-k2.5
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: glm5
    litellm_params:
      model: nvidia_nim/z-ai/glm5
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: nvidia_nim/z-ai/glm5
    litellm_params:
      model: nvidia_nim/z-ai/glm5
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: gemma-4-31b-it
    litellm_params:
      model: nvidia_nim/google/gemma-4-31b-it
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: nvidia_nim/google/gemma-4-31b-it
    litellm_params:
      model: nvidia_nim/google/gemma-4-31b-it
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: deepseek-v3.1-terminus
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v3.1-terminus
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

  - model_name: nvidia_nim/deepseek-ai/deepseek-v3.1-terminus
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v3.1-terminus
      api_key: os.environ/NVIDIA_NIM_API_KEY
      drop_params: true

litellm_settings:
  drop_params: true
  set_it_to_none_if_empty: true
